version: '2.4'
services:
    
  # https://github.com/Tob1as/docker-qwebirc
  qwebirc:
    #build:
    #  context: ./
    #  dockerfile: Dockerfile
    image: ghcr.io/tob1as/docker-qwebirc:latest
    container_name: qwebirc
    restart: unless-stopped
    ports:
      - 9090:9090/tcp
    environment:
      HTML_COMPILE: 1
    volumes:
      - ./config.py:/qwebirc/config.py:ro
      #- ./ssl:/ssl:ro
    healthcheck:
      test: ["CMD-SHELL", "nc -nzv -w 3 127.0.0.1 9090 || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3
    #command: [ "/bin/sh", "-c", "--", "while true; do sleep 60; done;" ]
    